# backend/tools/mock_data.py
# Real-looking mock data for Indian Amazon sellers

PRODUCTS = [
    {
        "asin": "B08N5WRWNW",
        "sku": "PHONE-CASE-001",
        "title": "Premium Silicone Case for iPhone 15 Pro Max",
        "current_stock": 8,
        "reorder_point": 20,
        "price": 599.0,
        "buy_box_percentage": 82.5,
        "status": "active",
        "category": "Electronics Accessories",
        "monthly_sales": 245,
    },
    {
        "asin": "B09B8YWXYZ",
        "sku": "CABLE-USBC-002",
        "title": "Nylon Braided USB-C Fast Charging Cable 3m",
        "current_stock": 145,
        "reorder_point": 30,
        "price": 299.0,
        "buy_box_percentage": 95.0,
        "status": "active",
        "category": "Electronics",
        "monthly_sales": 512,
    },
    {
        "asin": "B07XQXZABC",
        "sku": "EARBUDS-TWS-003",
        "title": "Wireless Earbuds 40Hr Battery ANC TWS",
        "current_stock": 3,
        "reorder_point": 15,
        "price": 1299.0,
        "buy_box_percentage": 0.0,
        "status": "suppressed",
        "category": "Electronics",
        "monthly_sales": 89,
    },
    {
        "asin": "B08KQPQDEF",
        "sku": "BAG-LAPTOP-004",
        "title": "Waterproof Laptop Backpack 15.6 inch Anti-Theft",
        "current_stock": 67,
        "reorder_point": 25,
        "price": 1599.0,
        "buy_box_percentage": 78.0,
        "status": "active",
        "category": "Bags & Luggage",
        "monthly_sales": 178,
    },
    {
        "asin": "B0CXYZ1234",
        "sku": "STAND-PHONE-005",
        "title": "Adjustable Mobile Phone Stand Holder Desk",
        "current_stock": 230,
        "reorder_point": 40,
        "price": 199.0,
        "buy_box_percentage": 91.0,
        "status": "active",
        "category": "Electronics Accessories",
        "monthly_sales": 634,
    },
]

REVIEWS = [
    {
        "review_id": "R3K9MXYZ001",
        "asin": "B08N5WRWNW",
        "rating": 2,
        "title": "Quality is very poor, broke in 1 week",
        "body": "The case cracked after just 7 days of normal use. The silicone feels very thin and cheap. Very disappointed for the price. Would not recommend to anyone.",
        "reviewer_name": "Rahul Sharma",
        "verified_purchase": True,
        "is_replied": False,
        "date": "2026-04-17",
    },
    {
        "review_id": "R3K9MXYZ002",
        "asin": "B09B8YWXYZ",
        "rating": 1,
        "title": "Stopped charging after 3 days - complete waste",
        "body": "I bought this cable expecting it to last but it stopped charging my phone after just 3 days. The connector feels loose from the beginning itself. Complete waste of money.",
        "reviewer_name": "Priya Mehta",
        "verified_purchase": True,
        "is_replied": False,
        "date": "2026-04-18",
    },
    {
        "review_id": "R3K9MXYZ003",
        "asin": "B08KQPQDEF",
        "rating": 5,
        "title": "Excellent bag! Highly recommend",
        "body": "Best laptop bag I have used. Very spacious, waterproof feature actually works, and the anti-theft lock is genius. Using daily for 3 months now.",
        "reviewer_name": "Amit Kumar",
        "verified_purchase": True,
        "is_replied": True,
        "date": "2026-04-15",
    },
    {
        "review_id": "R3K9MXYZ004",
        "asin": "B0CXYZ1234",
        "rating": 2,
        "title": "Falls easily, not stable at all",
        "body": "The stand falls whenever I touch the phone. Doesn't grip the surface at all on my glass desk. The rubber at bottom seems very weak.",
        "reviewer_name": "Sunita Patel",
        "verified_purchase": True,
        "is_replied": False,
        "date": "2026-04-19",
    },
]

AD_CAMPAIGNS = [
    {
        "campaign_id": "CAMP_SP_001",
        "campaign_name": "Phone Case - Broad Match Keywords",
        "campaign_type": "Sponsored Products",
        "acos": 68.5,
        "spend": 2850.0,
        "revenue": 4160.0,
        "impressions": 15420,
        "clicks": 312,
        "ctr": 2.02,
        "cvr": 3.85,
        "status": "active",
    },
    {
        "campaign_id": "CAMP_SP_002",
        "campaign_name": "Charger Cable - Exact Match",
        "campaign_type": "Sponsored Products",
        "acos": 18.2,
        "spend": 890.0,
        "revenue": 4890.0,
        "impressions": 8920,
        "clicks": 178,
        "ctr": 1.99,
        "cvr": 8.43,
        "status": "active",
    },
    {
        "campaign_id": "CAMP_SP_003",
        "campaign_name": "Earbuds - Auto Campaign",
        "campaign_type": "Sponsored Products",
        "acos": 145.0,
        "spend": 1200.0,
        "revenue": 827.0,
        "impressions": 22100,
        "clicks": 89,
        "ctr": 0.40,
        "cvr": 1.12,
        "status": "active",
    },
    {
        "campaign_id": "CAMP_SB_004",
        "campaign_name": "Laptop Bag - Sponsored Brand",
        "campaign_type": "Sponsored Brand",
        "acos": 22.5,
        "spend": 1580.0,
        "revenue": 7022.0,
        "impressions": 11200,
        "clicks": 245,
        "ctr": 2.19,
        "cvr": 6.53,
        "status": "active",
    },
    {
        "campaign_id": "CAMP_SP_005",
        "campaign_name": "Phone Stand - Broad + Phrase",
        "campaign_type": "Sponsored Products",
        "acos": 31.4,
        "spend": 740.0,
        "revenue": 2356.0,
        "impressions": 9800,
        "clicks": 196,
        "ctr": 2.0,
        "cvr": 5.1,
        "status": "active",
    },
]

ACCOUNT_HEALTH = {
    "order_defect_rate": 0.8,
    "pre_fulfillment_cancel_rate": 0.5,
    "late_shipment_rate": 3.2,
    "valid_tracking_rate": 98.5,
    "on_time_delivery": 96.2,
    "overall_status": "At Risk",
    "policy_violations": 0,
}
